In [1]:
import numpy as np
import pandas as pd

In [2]:
def funcao_sinal(u_potencial_de_ativacao):
    if(u_potencial_de_ativacao >= 0):
        return 1.
    return -1.

In [3]:
np.random.seed(17)
df = pd.read_csv('data/arquivo_tratado.csv', sep=';', header=None)
amostras = df.iloc[0:29,[0,1,2]].values
amostras = np.insert(amostras, 0, -1, axis=1)
pesos = np.random.uniform(-1, 1, amostras.shape[1])
rotulos = df.iloc[0:29,[-1]].values
print(amostras)
print(pesos)
print(rotulos)

[[-1.     -0.6508  0.1097  4.0009]
 [-1.     -1.4492  0.8896  4.4005]
 [-1.      2.085   0.6876 12.071 ]
 [-1.      0.2626  1.1476  7.7985]
 [-1.      0.6418  1.0234  7.0427]
 [-1.      0.2569  0.673   8.3265]
 [-1.      1.1155  0.6043  7.4446]
 [-1.      0.0914  0.3399  7.0677]
 [-1.      0.0121  0.5256  4.6316]
 [-1.     -0.0429  0.466   5.4323]
 [-1.      0.434   0.687   8.2287]
 [-1.      0.2735  1.0287  7.1934]
 [-1.      0.4839  0.4851  7.485 ]
 [-1.      0.4089 -0.1267  5.5019]
 [-1.      1.4391  0.1614  8.5843]
 [-1.     -0.9115 -0.1973  2.1962]
 [-1.      0.3654  1.0475  7.4858]
 [-1.      0.2144  0.7515  7.1699]
 [-1.      0.2013  1.0014  6.5489]
 [-1.      0.6483  0.2183  5.8991]
 [-1.     -0.1147  0.2242  7.2435]
 [-1.     -0.797   0.8795  3.8762]
 [-1.     -1.0625  0.6366  2.4707]
 [-1.      0.5307  0.1285  5.6883]
 [-1.     -1.22    0.7777  1.7252]
 [-1.      0.3957  0.1076  5.6623]
 [-1.     -0.1013  0.5989  7.1812]
 [-1.      2.4482  0.9455 11.2095]
 [-1.      2.0149  0

In [7]:
TAXA_DE_APRENDIZAGEM = 0.01
EPOCAS = 3000
existe_erro = False
pesos_iniciais = pesos

for epoca in range(EPOCAS):
    existe_erro = False
    for entradas in amostras:
        for d in rotulos:         
            produto = np.multiply(entradas, pesos)
            limiar = pesos[0]
            #print('produto', produto)
            #print('limiar', limiar)
            somatorio = np.sum(produto)
            #print('somatorio', somatorio)
            somatorio = somatorio - limiar
            #print('somatorio - limiar', somatorio)
            y_saida = funcao_sinal(somatorio)
            #print('y_saida',#y_saida)
            #print(d)
            if d != y_saida:
                existe_erro = True
                pesos = pesos + (TAXA_DE_APRENDIZAGEM * (d - y_saida) * entradas)
    if not existe_erro:
        break
print('epocas', epoca)
print("pesos iniciais", pesos_iniciais)
print("pesos finais", pesos)

epocas 2999
pesos iniciais [-0.37066999  0.18482551 -0.41835643 -0.14635928]
pesos finais [-0.13066999  0.04652951 -0.05621043 -0.13862928]
